version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: yarn install # run the `npm install` command
      - run: yarn build:frontend
  web-app:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run: echo "web-app"
workflows:
  version: 2
  review-app:
    jobs:
      - build
      - web-app
