version: '3.7'

services:
  #Backend api
  # smart-brain-api:
  #   container_name: backend
  #   build: ./
  #   command: yarn start
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./:/usr/smart-brain-api
  #     - /usr/smart-brain-api/node_modules

  #Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:5432

  #Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
