name: CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PM2
        run: npm i -g pm2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.KNOWN_HOSTS}}
      - name: Run deploy api & webapp
        run: cd packages/smart-brain-api && pm2 deploy production
